### ISSUE TITLE
Adding more than one LineItem 

### ISSUE THREAD

**Issue by jsjohnstone** [drpitman/PHP-Xero#2]
Hi there,

I'm just playing around with the PHP-Xero class at the moment - very cool stuff!

The only issue I've run into is that I'm not sure how to add more than one line item to an invoice. Obviously, rewriting the LineItem array each time just replaces the last LineItem. Have you got any ideas on a work-around for this?

Would really appreciate any thoughts!

Cheers,

Jamie.

**Comment by drpitman** [comment]
Have you tried this kind of thing?

$new_invoice = array(
    array(
        "Type"=>"ACCREC",
        "Contact" => array(
            "ContactID" => "[contact id]"
        ),
        "Date" => "2010-04-08",
        "DueDate" => "2010-04-30",
        "Status" => "SUBMITTED",
        "LineAmountTypes" => "Exclusive",
        "LineItems"=> array(
            "LineItem" => array(
                array(
                    "Description" => "This is line item 1",
                    "Quantity" => "2.0000",
                    "UnitAmount" => "250.00",
                    "AccountCode" => "200"
                ), 
                array(
                    "Description" => "This is line item 2",
                    "Quantity" => "1.0000",
                    "UnitAmount" => "300.00",
                    "AccountCode" => "200"
                )
            )
        )
    )
);

I haven't used exactly that in production code yet for creating invoices, but I've used the converse construction for reading multiple line items from invoices and it is working fine.

Enjoy :)

David.

**Comment by jsjohnstone** [comment]
Worked perfectly! Thanks for your help and the fantastic class!

Cheers,

Jamie.
